name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  Builds:
    runs-on: ubuntu-latest

    steps:
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      - uses: actions/checkout@v2
      - run: docker build . -f builder/Dockerfile -t scrape:latest
      - run: docker run --name=mscrp --rm -dit scrape:latest bash
      - run: docker cp mscrp:/scraper/ ./
      - run: tar -czf scrape.tar.gz scraper && tar -cf scrape.tar scraper
      - name: Create Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: Meta Scrape ${{ steps.get_version.outputs.VERSION }}
          files: |
            scrape.tar.gz
            scrape.tar
